version: '3.9'

services:
  map:
    image: 3liz/qgis-map-server:3.24
    environment:
      - QGSRV_SERVER_WORKERS=6
      - QGSRV_LOGGING_LEVEL=DEBUG
      - QGSRV_CACHE_ROOTDIR=/web
      - QGSRV_CACHE_SIZE=100
      - QGSRV_SERVER_TIMEOUT=300
    volumes:
      - ./data:/web
  mapproxy:
    image: kartoza/mapproxy
    environment:
      - PRODUCTION=true
      - PROCESSES=4
      - CHEAPER=2
      - THREADS=10
      - MAPPROXY_USER_ID=1000
      - MAPPROXY_GROUP_ID=1000
      - MULTI_MAPPROXY=true
      - ALLOW_LISTING=True
      - LOGGING=true
    volumes:
      - ./configuration:/mapproxy
      - ./configuration:/multi_mapproxy
    depends_on:
      - map
  nginx:
    image: nginx
    volumes:
      - ./web:/web
      - ./sites-enabled:/etc/nginx/conf.d:ro
    logging:
      driver: json-file
      options:
        max-size: 200m
        max-file: '10'
    depends_on:
      - mapproxy
      - map
    ports:
    - "80:80"







