name: build-latest
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'Dockerfile'
      - 'scripts/**'
      - 'build_data/**'
      - '.github/workflows/**'
  push:
    branches:
      - master
      - main
    paths:
      - 'Dockerfile'
      - 'scripts/**'
      - 'build_data/**'
      - '.github/workflows/**'

jobs:
  run-scenario-tests:
    if: |
      github.actor != 'dependabot[bot]' &&
      !(
        contains(github.event.pull_request.title, '[skip-release]') ||
        contains(github.event.comment.body, '/skiprelease')
      )
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mapproxy_version:
          - '==3.1.3'
        imageVersion:
          - image: 3.13.0
        scenario:
          - s3
          - proxy
          - multi_proxy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image for testing
        id: docker_build_testing_image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: false
          load: true
          tags: kartoza/mapproxy
          build-args: |
            IMAGE_VERSION=${{ matrix.imageVersion.image }}
            MAPPROXY_VERSION=${{ matrix.mapproxy_version }}
          cache-from: |
           type=gha,scope=test
           type=gha,scope=prod
          cache-to: type=gha,scope=test

      - name: Run scenario test ${{ matrix.scenario }}
        working-directory: scenario_tests/${{ matrix.scenario }}
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
          PRINT_TEST_LOGS: 1
        run: |
          bash ./test.sh

  push-internal-pr-images:
    if: |
      github.event_name == 'pull_request' && 
      github.event.pull_request.base.repo.url == github.event.pull_request.head.repo.url && 
      github.actor != 'dependabot[bot]'  &&
      !(
        contains(github.event.pull_request.title, '[skip-release]') ||
        contains(github.event.comment.body, '/skiprelease')
      )
    runs-on: ubuntu-latest
    needs: [ run-scenario-tests ]
    strategy:
      matrix:
        mapproxy_version:
          - '==3.1.3'
        imageVersion:
          - image: 3.13.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_REPO}}/mapproxy
          tags: |
            type=semver,pattern=\d.\d.\d
            type=ref,event=branch
            type=ref,event=pr
