name: deploy-image
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - build-latest
    branches:
      - develop
      - action
    types:
      - completed
jobs:
  deploy-image:
    runs-on: ubuntu-latest
    env:
      latest-ref: refs/heads/develop
    strategy:
      matrix:
        mapproxy_version:
          - '==1.16.0'
        imageVersion:
          - image: 3.11.5
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Get Current Date
        id: current_date
        shell: python
        run: |
          import datetime
          now = datetime.datetime.utcnow()
          print(f'::set-output name=formatted::{now:%Y.%m.%d}')

      - name: Replace '=='
        id: replace_double_equals
        run: |
          mapproxy_version="${{ matrix.mapproxy_version }}"
          mapproxy_version="${mapproxy_version//==/}"
          echo "::set-env name=formatted_mapproxy_version::$mapproxy_version"
        shell: bash

      - name: Build prod image
        id: docker_build_prod
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_REPO }}/mapproxy
            ${{ secrets.DOCKERHUB_REPO }}/mapproxy:${{ env.formatted_mapproxy_version }}
          build-args: |
            IMAGE_VERSION=${{ matrix.imageVersion.image }}
            MAPPROXY_VERSION=${{ env.formatted_mapproxy_version }}
          cache-from: |
            type=gha,scope=test
            type=gha,scope=prod
          cache-to: type=gha,scope=prod
